### ISSUE TITLE
Should we be tracking devices.json?

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/devtools-device-data#10]
The devices.json is the output of generation. If this is tracked (as it currently is) then pulling in multiple merges quickly becomes a pain since each PR is going to conflict with that generated file.

Perhaps a better setup would be:
- Add devices.json to gitignore.
- Pre-commit hook that does validation of all the JSON files (taking advantage of what is being discussed in issue #9)
- If we could do a post-merge/push hook to auto-generate the devices.json that would be nice. Falling short of that just have it has a part of the build process for the DevTools.

Any other ideas?

**Comment by paulirish** [comment]
travis is already set up to run the python script. would rather do that then force it into precommit.

i think that incoming PRs shouldn't update the devices.json

maybe we move it to /dist to make it clear?

**Comment by Garbee** [comment]
I mean, if someone is building it to test their changes it will end up in the commit. Since most of the time people just `git add -A` or similar when making a commit. Having it in another folder wouldn't help that since it is still being tracked.

I'm going to write a contributing.md file later this week for the repo. Maybe it is something we just point out there (since people _should_ read that before contributing) and leave it to rest unless it becomes a repeated problem.

**Comment by paulirish** [comment]
Yeahhh lets start there.
