### ISSUE TITLE
Nokia [Microsoft] Lumia Emulator Support

### ISSUE THREAD

**Issue by SheepDomination** [GoogleChrome/devtools-device-data#13]
Hi, Chrome Emulation models does not including, most if not all the Nokia/Microsoft Lumia Phones, including what I own, the 1520.  I'm in desperate need of this for the past week. I noticed some Lumia are listed, although some are missing particularly the 1520 or 1030 !

**Comment by dgozman** [comment]
Pull requests are welcome! Just add a directory with "device.json" file describing your device. Use other devices as examples.

**Comment by SheepDomination** [comment]
Sorry, I still don't understand ?

**Comment by Garbee** [comment]
I have a [mockup](https://gist.github.com/Garbee/40f3d2f87c86bc79feda) of the contributing guide I'm working on for the repository. Please take a look at that and see if it helps. Also let me know if anything doesn't make sense to sounds odd.

**Comment by SheepDomination** [comment]
Garbee - In the link you supplied;
Add a new folder that follows the naming contention, I add a sub-folder within the JSon folder which is the name of the device, correct ?
