### ISSUE TITLE
Import UA additions from upstream 

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/devtools-device-data#18]
In https://codereview.chromium.org/937303004/ I made a few changes
- dropped old and dead devices
- added new popular ones
- renamed a few things

sources:
- https://mixpanel.com/trends/#report/top_tablets
- http://bjango.com/articles/min-device-pixel-ratio/
- google

Need to update some things over here to match.

https://codereview.chromium.org/940193002/ updated some chrome UAs

**Comment by Garbee** [comment]
https://codereview.chromium.org/836743002/

This has also been made with some Blackberry updates. It should be merged up as well if a PR isn't made along with this already.

I am planning on handling this on Tuesday next week as well after I fix some breakage in other projects...
