### ISSUE TITLE
Nexus 5X and 6P dimensions are incorrect

### ISSUE THREAD

**Issue by devinkemper** [GoogleChrome/devtools-device-data#25]
The Nexus 5X and 6P dimensions appear to be incorrect, as well as the device pixel ratio for the 6P. They should be the following:

Nexus 5X: 412x732
Nexus 6P: 412x732 with a DPR of 3.5

**Comment by Garbee** [comment]
cc @paulirish and/or @dgozman to confirm the exact settings.

I don't have either of these devices available to test with. One of you _should_ be able to pull it off. :wink:

**Comment by addyosmani** [comment]
Do we have a reference for Nexus 5X: 412x732 Nexus 6P: 412x732 with a DPR of 3.5 that confirms this? (thanks for the PR!)

**Comment by hexalys** [comment]
@addyosmani 
There is one at: https://material.io/devices/
Some will probably show 412 instead of 411 depending the device and browser from 411.428px

**Comment by Garbee** [comment]
Looks like these have been changed upstream. I'm getting the expected parameters in the dev channel.
