### ISSUE TITLE
Help maintaining UAs

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/devtools-device-data#8]
It's easy for these UAs to fall out of date. 

We need an improved method of keeping these updated. 

We want the UAs to represent the latest stable version of Chrome & Safari on each device.

Any suggestions?

**Comment by coliff** [comment]
I wonder if it could make use of the https://github.com/WhichBrowser/WhichBrowser repo. It has a huge up-to-date database already and works really well (it powers the html5test.com site browser detection)

**Comment by paulirish** [comment]
potentially... we're doing the reverse though. instead of parsing we're
providing UAs and need to rev them.

e.g. it'd be great to use the Chrome Beta UA and push that update to master
when the beta goes stable every 6 weeks.

but i would like to use some open & maintained source if possible.
