### ISSUE TITLE
Validate using JSON Schema

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/devtools-device-data#9]
http://json-schema.org/examples.html
https://pypi.python.org/pypi/jsonschema

Should do this in the generate_ py script

**Comment by Garbee** [comment]
I'm giving this a shot today. Is it OK if we require pip to install the jsonschema package? Or should I find a way to include a local copy?

**Comment by paulirish** [comment]
Yup. travis is totally cool with using pip for that too. we'll just have to add it in the travis yml

**Comment by paulirish** [comment]
@Garbee currently the generate py script does a pretty manual validation so this will replace that one.

a few fields will likely end up being optional. e.g. the nexus 6/9 json's that addy just contributed doesnt have all fields and that's ok.

**Comment by marcoacierno** [comment]
What about https://github.com/rrev/devtools-device-data/commit/e7adbbcf371022c0c6ce9a080bddc5695837562c ? The `abs` check is done with the code (https://github.com/rrev/devtools-device-data/commit/2cc96789a8bd93a65cae742d22d09ef5ae71ce06).

I replicated the current behavior of the code.

If the scheme (or schema?) is OK, we should just throw away the entire python code except for images code rebase and `abs` check?

**Comment by Garbee** [comment]
I wouldn't have the schema in the generation file. Externalizing it makes a simple file to edit when the scheme is updated like I was [doing in my fork](https://github.com/Garbee/devtools-device-data/blob/feature/validation/device-scheme.json) if you just externalize that then it looks right.

**Comment by marcoacierno** [comment]
Ok, I moved it to an external file (https://github.com/rrev/devtools-device-data/commit/cb60b3de5e9d133c8b68b8071cdb312c7b87d4f8).

**Comment by Garbee** [comment]
So looks to me (Paul I'm sure will follow-up if anything else is needed for a good PR) like we just need the following to be done:
1. requirements.txt file in the root with the code area at the bottom of this message as the contents.
2. travis.yml to be updated to pip install requirements.txt before generating the script.
3. Optional: If you know how to squash commits I'd go ahead and do that so this is all one commit coming back.

Paul, we can deal with undoing the manual validation stuff in another PR to help keep things straightforward.

requirements.txt:

```
jsonschema==2.4.0
```

Install in travis.yml

```
install: pip install -r requirements.txt
```

**Comment by marcoacierno** [comment]
Okay, then as I already asked, what should I do with the Python code? The python code just validate the device json file so I think it's not needed anymore (except for abs check and image rebase)

Anyway I will do a commit with just image-rebase and abs check

**Comment by Garbee** [comment]
I had said we will do the removal of all the manual validation that isn't needed anymore in another PR to keep things specific. We don't really want too many things happening in a commit since if stuff breaks it is easier to rollback a commit or two and test vs going through a whole single PR of a dozen changes.

**Comment by marcoacierno** [comment]
Thanks, my bad I didn't understand what you said above :)

**Comment by paulirish** [comment]
@rrev 

you can kill that duplicated python code now.

also "schema" not "scheme"

@rrev open a PR when you're ready and we'll pick up the review from there.

**Comment by marcoacierno** [comment]
I did

**Comment by paulirish** [comment]
@rrev awesome thanks. We'll pick up over there.

**Comment by Garbee** [comment]
This should be closed since PR #11 was merged in.

Thanks again for the contribution @rrev.
